 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    ports:
      - "5050:5050"
    networks:
      - app-network
    volumes:
      - ./target:/app/target
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - sandbox
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped

  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: sandbox-container
    networks:
      - app-network
    volumes:
      - ./sandbox:/app/sandbox:rw
    tmpfs:
      - /tmp:exec,rw,size=50M
    environment:
      - SANDBOX_MAX_EXECUTION_TIME=10
      - SANDBOX_MAX_OUTPUT_SIZE=1048576
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep [i]nit.sh || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: /bin/bash -c "while true; do sleep 1; done"

networks:
  app-network:
    driver: bridge
